routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::post('login_test', [App\Http\Controllers\Auth\LoginController::class, 'authenticate']);

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/finger', [App\Http\Controllers\HomeController::class, 'finger'])->name('finger');

    Route::resource('fpUsers', App\Http\Controllers\FpUserController::class);
    Route::resource('fpAttendances', App\Http\Controllers\FpAttendanceController::class);
    Route::get('attendancetest', [App\Http\Controllers\HomeController::class, 'attendancetest']);
    Route::get('fpAttendances_sync', [App\Http\Controllers\FpAttendanceController::class, 'fpAttendances_sync'])->name('fpAttendances.sync');
    Route::get('fpUsers_sync', [App\Http\Controllers\FpUserController::class, 'fpuser_sync'])->name('fpUsers.sync');


    Route::resource('laporan', App\Http\Controllers\LaporanController::class);

    //view detail laporan
    Route::any('viewDetailAttendace/{id}', [App\Http\Controllers\ViewDetailAttendanceController::class, 'index'])->name('viewDetailAttendace');
});


Route::get('/user/dashboard', [App\Http\Controllers\User\homeController::class, 'index'])->name('dashboard')->middleware('is_user');
Route::any('/user/laporan/{id}', [App\Http\Controllers\User\laporanController::class, 'index'])->name('laporan')->middleware('is_user');
Route::any('/user/absen', [App\Http\Controllers\User\absenController::class, 'store'])->name('absen')->middleware('is_user');
Route::get('/user/login', [App\Http\Controllers\User\LoginUserController::class, 'index'])->name('user.login');
Route::post('/user/authenticate', [App\Http\Controllers\User\LoginUserController::class, 'authenticate'])->name('user.authenticate');




Route::resource('fpViewAttendances', App\Http\Controllers\FpViewAttendanceController::class);

app/Models/FpAttendance.php
<?php

namespace App\Models;

// use Eloquent as Model;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Class FpAttendance
 * @package App\Models
 * @version June 3, 2021, 8:49 am UTC
 *
 * @property string $id
 * @property string|\Carbon\Carbon $timestamp
 * @property integer $type
 */
class FpAttendance extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'fp_attendance';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];

    protected $primaryKey='pk';

    protected $appends = ['tanggal'];

    public $fillable = [
        'uid',
        'id',
        'timestamp',
        'type',
        'state',
        'mesin'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'uid' => 'integer',
        'id' => 'string',
        'timestamp' => 'datetime',
        'type' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'timestamp' => 'nullable',
        'type' => 'nullable|integer',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'deleted_at' => 'nullable'
    ];

 /*   public function getFpUserAttribute(){
        return FpUser::where('userid','like', $this->id."%")->first();
    }*/

    public function getTanggalAttribute(){
        return Carbon::parse($this->attributes['timestamp'])
        ->translatedFormat('l, d F Y H:s');
    }

    public function fp_user()
    {
        return $this->belongsTo(\App\Models\FpUser::class, 'id','id');
    }

}

app/Http/Controllers/FpAttendanceController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\FpAttendanceDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateFpAttendanceRequest;
use App\Http\Requests\UpdateFpAttendanceRequest;
use App\Models\FpAttendance;
use App\Models\FpUser;
use App\Repositories\FpAttendanceRepository;
use Carbon\Carbon;
// use Flash;
use App\Http\Controllers\AppBaseController;
use Illuminate\Support\Facades\DB;
use Laracasts\Flash\Flash;
use Rats\Zkteco\Lib\ZKTeco;
use Response;

class FpAttendanceController extends AppBaseController
{
    /** @var  FpAttendanceRepository */
    private $fpAttendanceRepository;

    public function __construct(FpAttendanceRepository $fpAttendanceRepo)
    {
        $this->fpAttendanceRepository = $fpAttendanceRepo;
    }

    /**
     * Display a listing of the FpAttendance.
     *
     * @param FpAttendanceDataTable $fpAttendanceDataTable
     * @return Response
     */
    public function index(FpAttendanceDataTable $fpAttendanceDataTable)
    {
        return $fpAttendanceDataTable->render('fp_attendances.index');
    }

    /**
     * Show the form for creating a new FpAttendance.
     *
     * @return Response
     */
    public function create()
    {
        $fpUsers=FpUser::pluck('name','id');
        return view('fp_attendances.create',compact('fpUsers'));
    }

    /**
     * Store a newly created FpAttendance in storage.
     *
     * @param CreateFpAttendanceRequest $request
     *
     * @return Response
     */
    public function store(CreateFpAttendanceRequest $request)
    {
        $input = $request->all();

        $fpAttendance = $this->fpAttendanceRepository->create($input);

        Flash::success('Fp Attendance saved successfully.');

        return redirect(route('fpAttendances.index'));
    }

    /**
     * Display the specified FpAttendance.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $fpAttendance = $this->fpAttendanceRepository->find($id);

        if (empty($fpAttendance)) {
            Flash::error('Fp Attendance not found');

            return redirect(route('fpAttendances.index'));
        }

        return view('fp_attendances.show')->with('fpAttendance', $fpAttendance);
    }

    /**
     * Show the form for editing the specified FpAttendance.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $fpAttendance = $this->fpAttendanceRepository->find($id);

        if (empty($fpAttendance)) {
            Flash::error('Fp Attendance not found');

            return redirect(route('fpAttendances.index'));
        }

        return view('fp_attendances.edit')->with('fpAttendance', $fpAttendance);
    }

    /**
     * Update the specified FpAttendance in storage.
     *
     * @param  int              $id
     * @param UpdateFpAttendanceRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateFpAttendanceRequest $request)
    {
        $fpAttendance = $this->fpAttendanceRepository->find($id);

        if (empty($fpAttendance)) {
            Flash::error('Fp Attendance not found');

            return redirect(route('fpAttendances.index'));
        }

        $fpAttendance = $this->fpAttendanceRepository->update($request->all(), $id);

        Flash::success('Fp Attendance updated successfully.');

        return redirect(route('fpAttendances.index'));
    }

    /**
     * Remove the specified FpAttendance from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $fpAttendance = $this->fpAttendanceRepository->find($id);

        if (empty($fpAttendance)) {
            Flash::error('Fp Attendance not found');

            return redirect(route('fpAttendances.index'));
        }

        $this->fpAttendanceRepository->delete($id);

        Flash::success('Fp Attendance deleted successfully.');

        return redirect(route('fpAttendances.index'));
    }

    public function fpAttendances_sync()
    {
        //Mesin2
        $zk2 = new ZKTeco(env("IP_FINGERPRINT_SECONDARY"));

        if(!$zk2->connect()){
            Flash::error('Koneksi dengan alat bermasalah (mesin2)');
            return redirect(route('fpAttendances.index'));
        }

        DB::transaction(function () use($zk2){
            foreach (array_chunk($zk2->getAttendance(),1000) as $t)
            {
                /*foreach ($t as $key=>$k)
                {
                    if(empty(FpUser::where('id',$k['id'])->first())){
                        unset($t[$key]);
                    }
                }*/

                collect($t)->each(function (array $row) {
                    $fp = FpAttendance::firstOrCreate(
                        ['uid' => $row['uid'],'mesin'=>'mesin2'],
                        ['id' => $row['id'],'timestamp' => $row['timestamp'],'type' => $row['type'],'state' => $row['state']]
                    );
                });
            }
            //$zk2->clearAttendance();
        });

        /*$t=array(array('nama'=>'eko'),array('nama'=>'dadang'),array('nama'=>'anton'));
        foreach ($t as $key=>&$k)
        {
            $k['mesin'] = 'mesin1';
            if(($k['nama']==='eko')){
                unset($t[$key]);
            }
        }

        dd($t);*/
        $zk = new ZKTeco(env("IP_FINGERPRINT"));

        if(!$zk->connect()){
            Flash::error('Koneksi dengan alat bermasalah.');
            return redirect(route('fpAttendances.index'));
        }
/*
        foreach ($zk->getAttendance() as $attendance){
            FpAttendance::create($attendance);
        }*/

        /*DB::transaction(function () use($zk){

        });*/
        //dd($zk->getAttendance());

        DB::transaction(function () use($zk){
        foreach (array_chunk($zk->getAttendance(),1000) as $t)
        {
            /*foreach ($t as &$k)
            {
                $k['mesin'] = 'mesin1';
            }*/

            /*foreach ($t as $key=>$k)
            {
                if(empty(FpUser::where('id',$k['id'])->first())){
                    unset($t[$key]);
                }
            }*/

            collect($t)->each(function (array $row) {
                $fp = FpAttendance::firstOrCreate(
                    ['uid' => $row['uid'],'mesin'=>'mesin1'],
                    ['id' => $row['id'],'timestamp' => $row['timestamp'],'type' => $row['type'],'state' => $row['state']]
                );
            });

            /*FpAttendance::upsert($t,
                [
                    'uid',
                    'mesin'
                ],
                [
                    'id',
                    'timestamp',
                    'type',
                    'state',
                ]
            );*/
        }
            //$zk->clearAttendance();
        });




        Flash::success('Fp Attendance Sync successfully.');
        return redirect(route('fpAttendances.index'));
    }
}

resources/views/fp_attendances/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Fp Attendance</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'fpAttendances.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('fp_attendances.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('fpAttendances.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/fp_attendances/datatables_actions.blade.php
{!! Form::open(['route' => ['fpAttendances.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('fpAttendances.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('fpAttendances.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/fp_attendances/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Fp Attendance</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($fpAttendance, ['route' => ['fpAttendances.update', $fpAttendance->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('fp_attendances.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('fpAttendances.index') }}" class="btn btn-default">Cancel</a>
            </div>

           {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/fp_attendances/fields.blade.php
<!-- Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id', 'Id:') !!}
    {!! Form::select('id', $fpUsers,null, ['class' => 'form-control']) !!}
</div>

<!-- Timestamp Field -->
<div class="form-group col-sm-6">
    {!! Form::label('timestamp', 'Timestamp:') !!}
    {!! Form::text('timestamp', null, ['class' => 'form-control','id'=>'timestamp']) !!}
</div>

{!! Form::hidden('mesin', 'mesin2') !!}


@push('page_scripts')
    <script type="text/javascript">
        $('#timestamp').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: true,
            sideBySide: true
        })
    </script>
@endpush

<!-- Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('type', 'Type:') !!}
    {!! Form::number('type', 0, ['class' => 'form-control']) !!}
</div>

resources/views/fp_attendances/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Fp Attendances</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('fpAttendances.sync') }}">
                        Sync Kehadiran
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('fp_attendances.table')

                <div class="card-footer clearfix float-right">
                    <div class="float-right">

                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/fp_attendances/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Fp Attendance Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('fpAttendances.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">

            <div class="card-body">
                <div class="row">
                    @include('fp_attendances.show_fields')
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/fp_attendances/show_fields.blade.php
<!-- Id Field -->
<div class="col-sm-12">
    {!! Form::label('id', 'Id:') !!}
    <p>{{ $fpAttendance->id }}</p>
</div>

<!-- Timestamp Field -->
<div class="col-sm-12">
    {!! Form::label('timestamp', 'Timestamp:') !!}
    <p>{{ $fpAttendance->timestamp }}</p>
</div>

<!-- Type Field -->
<div class="col-sm-12">
    {!! Form::label('type', 'Type:') !!}
    <p>{{ $fpAttendance->type }}</p>
</div>

resources/views/fp_attendances/table.blade.php
@section('third_party_stylesheets')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('third_party_scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection