routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::post('login_test', [App\Http\Controllers\Auth\LoginController::class, 'authenticate']);

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/finger', [App\Http\Controllers\HomeController::class, 'finger'])->name('finger');

    Route::resource('fpUsers', App\Http\Controllers\FpUserController::class);
    Route::resource('fpAttendances', App\Http\Controllers\FpAttendanceController::class);
    Route::get('attendancetest', [App\Http\Controllers\HomeController::class, 'attendancetest']);
    Route::get('fpAttendances_sync', [App\Http\Controllers\FpAttendanceController::class, 'fpAttendances_sync'])->name('fpAttendances.sync');
    Route::get('fpUsers_sync', [App\Http\Controllers\FpUserController::class, 'fpuser_sync'])->name('fpUsers.sync');


    Route::resource('laporan', App\Http\Controllers\LaporanController::class);

    //view detail laporan
    Route::any('viewDetailAttendace/{id}', [App\Http\Controllers\ViewDetailAttendanceController::class, 'index'])->name('viewDetailAttendace');
});


Route::get('/user/dashboard', [App\Http\Controllers\User\homeController::class, 'index'])->name('dashboard')->middleware('is_user');
Route::any('/user/laporan/{id}', [App\Http\Controllers\User\laporanController::class, 'index'])->name('laporan')->middleware('is_user');
Route::any('/user/absen', [App\Http\Controllers\User\absenController::class, 'store'])->name('absen')->middleware('is_user');
Route::get('/user/login', [App\Http\Controllers\User\LoginUserController::class, 'index'])->name('user.login');
Route::post('/user/authenticate', [App\Http\Controllers\User\LoginUserController::class, 'authenticate'])->name('user.authenticate');




Route::resource('fpViewAttendances', App\Http\Controllers\FpViewAttendanceController::class);

app/Models/FpUser.php
<?php

namespace App\Models;

// use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Class FpUser
 * @package App\Models
 * @version June 3, 2021, 8:35 am UTC
 *
 * @property string $userid
 * @property string $name
 * @property integer $role
 * @property string $password
 * @property string $cardno
 */
class FpUser extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'fp_user';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];

    protected $primaryKey='uid';


    public $fillable = [
        'uid',
        'id',
        'userid',
        'name',
        'role',
        'password',
        'cardno'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'uid' => 'integer',
        'userid' => 'string',
        'name' => 'string',
        'role' => 'integer',
        'password' => 'string',
        'cardno' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'userid' => 'nullable|string|max:255',
        'name' => 'nullable|string|max:255',
        'role' => 'nullable|integer',
        'password' => 'nullable|string|max:255',
        'cardno' => 'nullable|string|max:255',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'deleted_at' => 'nullable'
    ];

}

app/Http/Controllers/FpUserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateFpUserRequest;
use App\Http\Requests\UpdateFpUserRequest;
use App\Models\FpUser;
use App\Repositories\FpUserRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
// use Flash;
use Illuminate\Support\Facades\DB;
use Laracasts\Flash\Flash;
use Rats\Zkteco\Lib\ZKTeco;
use Response;

class FpUserController extends AppBaseController
{
    /** @var  FpUserRepository */
    private $fpUserRepository;

    public function __construct(FpUserRepository $fpUserRepo)
    {
        $this->fpUserRepository = $fpUserRepo;
    }

    /**
     * Display a listing of the FpUser.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $fpUsers = $this->fpUserRepository->all()->sortBy('name');

        return view('fp_users.index')
            ->with('fpUsers', $fpUsers);
    }

    /**
     * Show the form for creating a new FpUser.
     *
     * @return Response
     */
    public function create()
    {
        return view('fp_users.create');
    }

    /**
     * Store a newly created FpUser in storage.
     *
     * @param CreateFpUserRequest $request
     *
     * @return Response
     */
    public function store(CreateFpUserRequest $request)
    {
        $input = $request->all();

        $fpUser = $this->fpUserRepository->create($input);

        Flash::success('Fp User saved successfully.');

        return redirect(route('fpUsers.index'));
    }

    /**
     * Display the specified FpUser.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $fpUser = $this->fpUserRepository->find($id);

        if (empty($fpUser)) {
            Flash::error('Fp User not found');

            return redirect(route('fpUsers.index'));
        }

        return view('fp_users.show')->with('fpUser', $fpUser);
    }

    /**
     * Show the form for editing the specified FpUser.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $fpUser = $this->fpUserRepository->find($id);

        if (empty($fpUser)) {
            Flash::error('Fp User not found');

            return redirect(route('fpUsers.index'));
        }

        return view('fp_users.edit')->with('fpUser', $fpUser);
    }

    /**
     * Update the specified FpUser in storage.
     *
     * @param int $id
     * @param UpdateFpUserRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateFpUserRequest $request)
    {
        $fpUser = $this->fpUserRepository->find($id);

        if (empty($fpUser)) {
            Flash::error('Fp User not found');

            return redirect(route('fpUsers.index'));
        }

        $fpUser = $this->fpUserRepository->update($request->all(), $id);

        Flash::success('Fp User updated successfully.');

        return redirect(route('fpUsers.index'));
    }

    /**
     * Remove the specified FpUser from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $fpUser = $this->fpUserRepository->find($id);

        if (empty($fpUser)) {
            Flash::error('Fp User not found');

            return redirect(route('fpUsers.index'));
        }

        $this->fpUserRepository->delete($id);

        Flash::success('Fp User deleted successfully.');

        return redirect(route('fpUsers.index'));
    }

    public function fpuser_sync(){
        $zk = new ZKTeco(env("IP_FINGERPRINT"));

        if(!$zk->connect()){
            Flash::error('Koneksi dengan alat bermasalah.');
            return redirect(route('fpUsers.index'));
        }


        //return $zk->getUser();
        DB::transaction(function () use($zk){
            $users=[];
            foreach ($zk->getUser() as $user){
                $user['id']=substr($user['userid'],0,9);
                array_push($users,$user);
            }

            FpUser::upsert($users,[
                'uid',
                'id',
                'userid',
                'name',
                'role',
                'password',
                'cardno'
            ],['name','id']);
        });


        Flash::success('Fp User Sync successfully.');
        return redirect(route('fpUsers.index'));
    }

    public function fpuser_sync_test(){
        $zk = new ZKTeco(env("IP_FINGERPRINT"));
        $zk->connect();

        /*foreach ($zk->getUser() as $user){
            $user['id']=substr($user['userid'],0,9);

        }*/
        DB::transaction(function () use($zk){
            FpUser::upsert($zk->getUser(),[
                'uid',
                'id',
                'userid',
                'name',
                'role',
                'password',
                'cardno'
            ],['name']);
        });


        Flash::success('Fp User Sync successfully.');
        return redirect(route('fpUsers.index'));
    }
}

resources/views/fp_users/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Fp User</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'fpUsers.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('fp_users.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('fpUsers.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/fp_users/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Fp User</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($fpUser, ['route' => ['fpUsers.update', $fpUser->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('fp_users.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('fpUsers.index') }}" class="btn btn-default">Cancel</a>
            </div>

           {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/fp_users/fields.blade.php
<!-- Userid Field -->
<div class="form-group col-sm-6">
    {!! Form::label('userid', 'Userid:') !!}
    {!! Form::text('userid', null, ['class' => 'form-control','maxlength' => 255,'maxlength' => 255]) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control','maxlength' => 255,'maxlength' => 255]) !!}
</div>

<!-- Role Field -->
<div class="form-group col-sm-6">
    {!! Form::label('role', 'Role:') !!}
    {!! Form::number('role', null, ['class' => 'form-control']) !!}
</div>

<!-- Password Field -->
<div class="form-group col-sm-6">
    {!! Form::label('password', 'Password:') !!}
    {!! Form::password('password', ['class' => 'form-control','maxlength' => 255,'maxlength' => 255]) !!}
</div>

<!-- Cardno Field -->
<div class="form-group col-sm-6">
    {!! Form::label('cardno', 'Cardno:') !!}
    {!! Form::text('cardno', null, ['class' => 'form-control','maxlength' => 255,'maxlength' => 255]) !!}
</div>

resources/views/fp_users/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Fp Users</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('fpUsers.sync') }}">
                        Sync Data Pengguna
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('fp_users.table')

                <div class="card-footer clearfix float-right">
                    <div class="float-right">

                    </div>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/fp_users/login.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ config('app.name') }}</title>

    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"
          integrity="sha512-0S+nbAYis87iX26mmj/+fWt1MmaKCv80H+Mbo+Ne7ES4I6rxswpfnC6PxmLiw33Ywj2ghbtTw0FkLbMWqh4F7Q=="
          crossorigin="anonymous"/>

    <!-- AdminLTE -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.0.5/css/adminlte.min.css"
          integrity="sha512-rVZC4rf0Piwtw/LsgwXxKXzWq3L0P6atiQKBNuXYRbg2FoRbSTIY0k2DxuJcs7dk4e/ShtMzglHKBOJxW8EQyQ=="
          crossorigin="anonymous"/>

    <!-- iCheck -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/icheck-bootstrap/3.0.1/icheck-bootstrap.min.css"
          integrity="sha512-8vq2g5nHE062j3xor4XxPeZiPjmRDh6wlufQlfC6pdQ/9urJkU07NM0tEREeymP++NczacJ/Q59ul+/K2eYvcg=="
          crossorigin="anonymous"/>

</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="{{ url('/home') }}"><b>{{ config('app.name') }}</b></a>
    </div>

    <!-- /.login-logo -->

    <!-- /.login-box-body -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Sign in to start your session</p>

            <form method="post" action="{{ route('user.authenticate') }}">
                @csrf

                <div class="input-group mb-3">
                    <input type="text"
                           name="userid"
                           value="{{ old('userid') }}"
                           placeholder="userid"
                           class="form-control">
                    <div class="input-group-append">
                        <div class="input-group-text"><span class="fas fa-envelope"></span></div>
                    </div>
                    @error('email')
                    <span class="error invalid-feedback">{{ $message }}</span>
                    @enderror
                </div>

                <div class="input-group mb-3">
                    <input type="password"
                           name="password"
                           placeholder="Password"
                           class="form-control @error('password') is-invalid @enderror">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                    @error('password')
                    <span class="error invalid-feedback">{{ $message }}</span>
                    @enderror

                </div>

                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input type="checkbox" id="remember">
                            <label for="remember">Remember Me</label>
                        </div>
                    </div>

                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                    </div>

                </div>
            </form>
        </div>
        <!-- /.login-card-body -->
    </div>

</div>
<!-- /.login-box -->

<!-- AdminLTE App -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.0.5/js/adminlte.min.js"
        integrity="sha512-++c7zGcm18AhH83pOIETVReg0dr1Yn8XTRw+0bWSIWAVCAwz1s2PwnSj4z/OOyKlwSXc4RLg3nnjR22q0dhEyA=="
        crossorigin="anonymous"></script>

</body>
</html>

resources/views/fp_users/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Fp User Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('fpUsers.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">

            <div class="card-body">
                <div class="row">
                    @include('fp_users.show_fields')
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/fp_users/show_fields.blade.php
<!-- Userid Field -->
<div class="col-sm-12">
    {!! Form::label('userid', 'Userid:') !!}
    <p>{{ $fpUser->userid }}</p>
</div>

<!-- Name Field -->
<div class="col-sm-12">
    {!! Form::label('name', 'Name:') !!}
    <p>{{ $fpUser->name }}</p>
</div>

<!-- Role Field -->
<div class="col-sm-12">
    {!! Form::label('role', 'Role:') !!}
    <p>{{ $fpUser->role }}</p>
</div>

<!-- Password Field -->
<div class="col-sm-12">
    {!! Form::label('password', 'Password:') !!}
    <p>{{ $fpUser->password }}</p>
</div>

<!-- Cardno Field -->
<div class="col-sm-12">
    {!! Form::label('cardno', 'Cardno:') !!}
    <p>{{ $fpUser->cardno }}</p>
</div>

resources/views/fp_users/table.blade.php
<div class="table-responsive">
    <table class="table" id="fpUsers-table">
        <thead>
            <tr>
            <th>No</th>
                <th>Userid</th>
                <th>ID</th>
        <th>Name</th>
        <th>Role</th>
        <th>Password</th>
        <th>Cardno</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php $no = 0; ?>
        @foreach($fpUsers as $fpUser)
        <?php $no++; ?>
            <tr>
                <td>{{ $no }}</td>
                <td>{{ $fpUser->userid }}</td>
                <td>{{ $fpUser->id }}</td>
            <td>{{ $fpUser->name }}</td>
            <td>{{ $fpUser->role }}</td>
            <td>{{ $fpUser->password }}</td>
            <td>{{ $fpUser->cardno }}</td>
                <td width="120">
                    {!! Form::open(['route' => ['fpUsers.destroy', $fpUser->uid], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('fpUsers.show', [$fpUser->uid]) }}" class='btn btn-default btn-xs'>
                            <i class="far fa-eye"></i>
                        </a>
                        <a href="{{ route('fpUsers.edit', [$fpUser->uid]) }}" class='btn btn-default btn-xs'>
                            <i class="far fa-edit"></i>
                        </a>
                        {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>